name: Send Workflow Logs via Email

on:
  workflow_run:
    workflows: ["CI/CD Workflow"]  # Nom de votre workflow principal
    types: [completed]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get logs of the latest workflow
        run: |
          gh run list --workflow "CI/CD Workflow" --limit 1 > workflow_id.txt
          WORKFLOW_ID=$(awk 'NR==2{print $7}' workflow_id.txt)
          gh run view $WORKFLOW_ID --log > workflow.log

      - name: Send Email with Logs
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Workflow Logs for ${{ github.repository }}"
          body: |
            Hello Team,

            Please find attached the logs of the recent workflow run.

            Best Regards,
            GitHub Actions Bot
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          secure: true
          attachments: workflow.log
